services:
  web:
    build:
      context: .
    image: buckpal_im
    container_name: buckpal
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/buckpal
    volumes:
      - .:/app  # ←ローカルのプロジェクトフォルダを/appにマウント
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: buckpal_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: buckpal
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  test_db:
    image: postgres:15-alpine
    container_name: buckpal_test_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: buckpal_test
    ports:
      - "5433:5432"
    volumes:
      - test-postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  test-postgres-data: